name: Custom HTTP Server

on:
  workflow_dispatch: # This makes it manually triggered

jobs:
  setup-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup ngrok
      run: |
        curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
        echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
        sudo apt update
        sudo apt install ngrok

    - name: Auth ngrok
      run: ngrok authtoken 2N5KFYmyocPObelDKx26R1e2gfP_MiFweWSd9A8CbrC1E9Ef
      
    - name: Create simple HTTP server script
      run: |
        cat << EOF > simple_http_server.py
        import http.server
        import socketserver
        import os

        PORT = 8080
        web_dir = os.path.join(os.path.dirname(__file__), 'web')
        os.makedirs(web_dir, exist_ok=True)
        os.chdir(web_dir)

        Handler = http.server.SimpleHTTPRequestHandler

        with socketserver.TCPServer(("", PORT), Handler) as httpd:
            print("serving at port", PORT)
            httpd.serve_forever()
        EOF

    - name: Start custom HTTP server in the background
      run: |
        python3 simple_http_server.py &

    - name: Expose server using ngrok
      run: |
        ngrok http 8080 & # assuming the custom HTTP server is running on 8080
        sleep 10 # give some time for ngrok to establish the tunnel
        curl http://localhost:4040/api/tunnels | jq '.tunnels[0].public_url'

    - name: Download files
      run: |
        wget https://github.com/GuinnessShep/LTSC-ADD-Microsoft-Store/releases/download/69/ltscaddstore-1.0.4-py3-none-any-eng.whl -P web/
        wget https://github.com/GuinnessShep/LTSC-ADD-Microsoft-Store/releases/download/69/ltscaddstore-english-1.0.4.tar.gz -P web/

    - name: Keep runner active
      run: sleep infinity
